apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: storage-system
spec:
  template:
    spec:
      containers:
      - name: minio
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
