apiVersion: v1
kind: Secret
metadata:
  name: graylog-secrets
  namespace: logging-system
  labels:
    app.kubernetes.io/name: graylog
type: Opaque
stringData:
  # ⚠️ PLACEHOLDER - REPLACE WITH SEALEDSECRET!
  # Generate password_secret (96 chars):
  # pwgen -N 1 -s 96
  graylog-password-secret: "GENERATE_96_CHAR_SECRET_FOR_GRAYLOG"
  
  # ⚠️ PLACEHOLDER - REPLACE WITH SEALEDSECRET!
  # Generate root password hash (SHA256):
  # echo -n "your_password" | sha256sum
  graylog-root-password-sha2: "GENERATE_SHA256_HASH_OF_ROOT_PASSWORD"
  
  # ⚠️ PLACEHOLDER - REPLACE WITH SEALEDSECRET!
  # MongoDB credentials
  mongodb-root-password: "GENERATE_STRONG_SECRET"
  mongodb-password: "GENERATE_STRONG_SECRET"
  
  # ⚠️ PLACEHOLDER - REPLACE WITH SEALEDSECRET!
  # Elasticsearch credentials
  elasticsearch-password: "GENERATE_STRONG_SECRET"
