apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-postgresql-data
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
