apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-postgresql
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/component: postgresql
spec:
  serviceName: zabbix-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix
        app.kubernetes.io/component: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: "zabbix"
        - name: POSTGRES_DB
          value: "zabbix"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-password
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - zabbix
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - zabbix
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: zabbix
        app.kubernetes.io/component: postgresql
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 50Gi
