apiVersion: v1
kind: Secret
metadata:
  name: network-ad-admin-secret
  namespace: core-auth
  labels:
    app.kubernetes.io/name: network-ad
    app.kubernetes.io/component: samba-ad-dc
    app.kubernetes.io/part-of: core-services
type: Opaque
stringData:
  # PLACEHOLDER - Replace with SealedSecret in production overlay!
  # Generate strong password: openssl rand -base64 32
  admin-password: "CHANGE_ME_IN_PRODUCTION"
