apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetfence
  namespace: identity-system
spec:
  template:
    spec:
      containers:
      - name: packetfence
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "4Gi"
            cpu: "4000m"
