apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  namespace: core-network
spec:
  template:
    spec:
      containers:
      - name: bind9
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
