apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-postgresql
  namespace: monitoring-system
spec:
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitoring-system
spec:
  template:
    spec:
      containers:
      - name: zabbix-server
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: monitoring-system
spec:
  template:
    spec:
      containers:
      - name: zabbix-web
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
