apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: network-ad-dc
  namespace: core-auth
spec:
  template:
    spec:
      containers:
      - name: samba-ad-dc
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
