apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-ad-dc
  namespace: identity-system
spec:
  template:
    spec:
      containers:
      - name: samba-ad-dc
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
          limits:
            memory: "16Gi"
            cpu: "8000m"
