apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-ad-dc
  namespace: identity-system
  labels:
    app.kubernetes.io/name: user-ad
    app.kubernetes.io/component: samba-ad-dc
    app.kubernetes.io/part-of: user-services
    app.kubernetes.io/version: "4.18"
spec:
  serviceName: user-ad-headless
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: user-ad
      app.kubernetes.io/component: samba-ad-dc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-ad
        app.kubernetes.io/component: samba-ad-dc
        app.kubernetes.io/part-of: user-services
        app.kubernetes.io/version: "4.18"
    spec:
      hostname: user-ad-dc
      subdomain: user-ad-headless
      
      securityContext:
        fsGroup: 0
      
      containers:
      - name: samba-ad-dc
        image: docker.io/ghcr.io/servercontainers/samba:4.18-latest
        imagePullPolicy: IfNotPresent
        
        env:
        - name: SAMBA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-ad-admin-secret
              key: admin-password
        
        - name: SAMBA_REALM
          value: "AD.ZSEL.OPOLE.PL"
        
        - name: SAMBA_DOMAIN
          value: "ZSEL"
        
        - name: SAMBA_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
        ports:
        - name: ldap
          containerPort: 389
          protocol: TCP
        - name: ldaps
          containerPort: 636
          protocol: TCP
        - name: kerberos-tcp
          containerPort: 88
          protocol: TCP
        - name: kerberos-udp
          containerPort: 88
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: smb
          containerPort: 445
          protocol: TCP
        - name: netbios-ns
          containerPort: 137
          protocol: UDP
        - name: netbios-dgm
          containerPort: 138
          protocol: UDP
        - name: netbios-ssn
          containerPort: 139
          protocol: TCP
        
        volumeMounts:
        - name: samba-data
          mountPath: /var/lib/samba
        - name: smb-config
          mountPath: /etc/samba/smb.conf
          subPath: smb.conf
        - name: init-script
          mountPath: /usr/local/bin/init-domain.sh
          subPath: init-domain.sh
        
        command: ["/bin/bash"]
        args: ["-c", "chmod +x /usr/local/bin/init-domain.sh && /usr/local/bin/init-domain.sh"]
        
        livenessProbe:
          tcpSocket:
            port: 389
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          tcpSocket:
            port: 389
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
      
      volumes:
      - name: smb-config
        configMap:
          name: user-ad-smb-config
      - name: init-script
        configMap:
          name: user-ad-init-script
          defaultMode: 0755
  
  volumeClaimTemplates:
  - metadata:
      name: samba-data
      labels:
        app.kubernetes.io/name: user-ad
        app.kubernetes.io/component: samba-ad-dc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 100Gi
