apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chrony
  namespace: core-network
spec:
  template:
    spec:
      containers:
      - name: chrony
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
