apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-services-app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core-services
  
  source:
    repoURL: https://github.com/zsel-opole/zsel-opole-org.git
    targetRevision: main
    path: infrastruktura-k3s/gitops/argocd/apps
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true      # Remove resources deleted from Git
      selfHeal: true   # Revert manual changes
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences that don't matter
  ignoreDifferences:
    - group: "*"
      kind: Secret
      jsonPointers:
        - /data
  
  # Health checks
  info:
    - name: Description
      value: "Root application that deploys all network services"
    - name: Maintainer
      value: "Łukasz Kołodziej <lkolodziej@aircloud.pl>"
    - name: Documentation
      value: "https://github.com/zsel-opole/zsel-opole-org/blob/main/infrastruktura-k3s/gitops/README.md"
