apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: storage-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
spec:
  serviceName: minio-headless
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: storage
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2024-01-01T16-36-33Z
        args:
        - server
        - http://minio-{0...3}.minio-headless.storage-system.svc.cluster.local/data
        - --console-address
        - ":9001"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-root-credentials
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-root-credentials
              key: MINIO_ROOT_PASSWORD
        - name: MINIO_DISTRIBUTED_MODE_ENABLED
          value: "yes"
        - name: MINIO_DISTRIBUTED_NODES
          value: "4"
        - name: MINIO_STORAGE_CLASS_STANDARD
          value: "EC:2"  # N/2 data shards + N/2 parity shards (4 nodes = 2+2)
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        - name: MINIO_SERVER_URL
          value: "http://192.168.255.70:9000"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://192.168.255.70:9001"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 2500Gi  # 2.5TB per node × 4 = 10TB total
